gcc main.c libftprintf.a -fsanitize=address -g3 
./a.out "%s" "Bonjour"
./a.out "% s" "Bonjour"
./a.out "% 2s" "Bonjour"
./a.out "% 5.2s" "Bonjour"
./a.out "% 2.5s" "Bonjour"
./a.out "%2.5s" "Bonjour"
./a.out "% +2.5s" "Bonjour"
./a.out "% 2.5s" "Bonjour"
./a.out "%hhx" "340"
./a.out "%zx" "340"
./a.out "%s" "❤ ☀ ☆ ☂ ☻ ♞ "
./a.out "%ls" "❤ ☀ ☆ ☂ ☻ ♞ "
./a.out "%s" "❤"
./a.out "%C" "❤ ☀"
./a.out "{%10R}" "Bonjour"
./a.out "{%010R}" "Bonjour"
./a.out "{%0 -10R}" "Bonjour"
